### ISSUE TITLE
Please add following features to it

### ISSUE THREAD

**Issue by ramanveerji** [irojkov-ph/GSAbot#1]
1. Add heroku support
2. searching and downloading of research papers in pdf format

**Comment by irojkov-ph** [comment]
Thanks for the suggestions :) I must push a new version of the project (hopefully before the end of the year).
Heroku support is planned as well but probably for next year, sorry.

**Comment by irojkov-ph** [comment]
I close this issue since the first point is addressed in the new release and the second one was never part of the project. Several other bots are performing this kind of tasks very well.

**Comment by ramanveerji** [comment]
> I close this issue since the first point is addressed in the new release and the second one was never part of the project. Several other bots are performing this kind of tasks very well.

Can you give any of the reference to that bot?

**Comment by irojkov-ph** [comment]
Try out: [@scihubot](https://t.me/scihubbot)
